# ---------- Build stage ----------
FROM node:20-alpine AS builder
WORKDIR /app

# Copy local frontend code
COPY project-frontend .

# Accept API URL as build argument
ARG REACT_APP_API_URL
ENV REACT_APP_API_URL=$REACT_APP_API_URL

# Install dependencies and build
RUN npm install
RUN npm run build

# ---------- Run stage ----------
FROM nginx:alpine
WORKDIR /usr/share/nginx/html

# Copy built frontend files
COPY --from=builder /app/dist ./

# Copy nginx config
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
